--batch-file play.list
#-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'
-i
-f 'bv*[height<=720]+(ba[language^=en]/ba)'
#-f 'bv*[height<=800]+ba' 
# https://askubuntu.com/questions/486297/how-to-select-video-quality-from-youtube-dl/1097056#1097056
# -f best
# -f 22/18
--merge-output-format mp4
# --write-auto-sub
# --all-subs

# --external-downloader aria2c # 调用外部下载工具
# --external-downloader-args "-x 16 -k 1M"

--embed-subs
--write-sub
--write-auto-sub
--sub-lang "zh,zh.*,en,en.*"
# --skip-download # 不下载视频
# --embed-thumbnail # 嵌入视频预览的图片
--add-metadata
# --split-chapters
--sleep-requests 0.75
--sleep-interval 5
--max-sleep-interval 10
--windows-filenames
--output "./downloads/W_%(id)s.%(ext)s"
# --output "chapter:./downloads/%(title)s/%(section_number)03d. %(section_title)s.%(ext)s"
--proxy socks5://127.0.0.1:10808
--continue
