# 使用的 actions:
# https://github.com/marketplace/actions/automatic-releases
name: Main

on:
  push:
    paths:
      - play.list
  # schedule:
  #   - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl rar python3 atomicparsley aria2 wget unzip -y
          sudo wget -O xray.zip https://github.com/XTLS/Xray-core/releases/download/v24.9.19/Xray-linux-64.zip
          sudo unzip -o ./xray.zip
          sudo chmod +x ./xray
          sudo wget -O config.json https://gist.githubusercontent.com/efrancis74/a07162d05beba30ce061ed898a3e3642/raw/config.json
          sudo sleep 2
          sudo nohup ./xray -c ./config.json >/dev/null 2>&1 &	
          sudo sleep 2
          sudo curl -sS http://ip-api.com/json --preproxy socks5://127.0.0.1:10808
          sudo sleep 2
          sudo curl -LJO https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          sudo chmod +x ./yt-dlp
          ./yt-dlp --config-location dl.conf
          sudo sleep 2
          sudo rm geoip.dat geosite.dat xray xray.zip config.json yt-dlp
          sudo sleep 2
          sudo chmod +x ./spfiles.sh
          ./spfiles.sh

      # Add, commit, then push the new file to the repo
      - name: Adds the new log file to the repo
        run: git add .
      - name: Commit change to repo
        run: git -c user.email="${{ secrets.EMAIL }}" -c user.name="${{ secrets.USERNAME }}" commit -am "Add 1st file again"
      - name: Push change to repo
        run: git push origin main	
  
